
[colors.bright]
black=   '0x4c4c4c'
red=     '0xc49ea0'
green=   '0x9ec49f'
yellow=  '0xc4c19e'
blue=    '0xa39ec4'
magenta= '0xc49ec4'
cyan=    '0x9ec3c4'
white=   '0xf5f5f5'

[colors.cursor]
cursor = "0xc9d1d9"
text = "0x0d1117"

[colors.normal]
black=   '0x262626'
red=     '0xac8a8c'
green=   '0x8aac8b'
yellow=  '0xaca98a'
blue=    '0x8f8aac'
magenta= '0xac8aac'
cyan=    '0x8aabac'
white=   '0xe7e7e7'


[colors.primary]
background = "#0f1014"
foreground = "#cccccc"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.25"

[font]
size = 11.1

[font.bold]
family = "JetBrainsMono NF"


[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Bold"

[font.normal]
family = "JetBrainsMono NF"
style = "Bold"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"
# opacity=0.8

[window.padding]
x = 0
y = 0
