
[colors.bright]
black = "0x6e7681"
blue = "0x79c0ff"
cyan = "0x39c5cf"
green = "0x79c0ff"
magenta = "0xbc8cff"
red = "0xe33333"
white = "0xb1bac4"
yellow = "0xe33333"

[colors.cursor]
cursor = "0xc9d1d9"
text = "0x0d1117"

[colors.normal]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x58a6ff"
magenta = "0xbc8cff"
red = "0xe33333"
white = "0xb1bac4"

[colors.primary]
 # background = "#0f1014"
background = "#0a0b0c"
foreground = "#cccccc"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 10.6

[font.bold]
family = "JetBrainsMono NF SemiBold"

[font.bold_italic]
family = "JetBrainsMono NF SemiBold"
style = "SemiBold"

[font.italic]
family = "JetBrainsMono NF SemiBold"
style = "SemiBold"

[font.normal]
family = "JetBrainsMono NF SemiBold"
style = "SemiBold"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"
# opacity=0.8

[window.padding]
x = 0 
y = 0
